# Generated by Django 5.1.2 on 2024-12-09 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('desbloqueada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('pontuacao_total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pontuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao', models.IntegerField()),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fase')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jogador')),
            ],
        ),
    ]
